version: 0.2
env:
  secrets-manager: 
    TOKEN: firstSecret:tokenForSonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws1 -Dsonar.organization=javaprojectaws-course -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=javaprojectaws | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
        tar -xvf ZAP_2.16.0_Linux.tar.gz
        cd ZAP_2.16.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html 
artifacts:
  files:
    - zap_report.html